### ISSUE TITLE
Is it possible to suppress the debug logs

### ISSUE THREAD

**Issue by byteshiva** [veggiedefender/torrent-client#1]
Is it possible to suppress the debug logs? Also, I'd like to run this as a background job, maybe via some go or python or javascript async code.

**Comment by crimist** [comment]
Running `torrent-client <.torrent> <file> &` will run it in the background (note the `&`). You can read more about running a background process in bash [here](https://www.digitalocean.com/community/tutorials/how-to-use-bash-s-job-control-to-manage-foreground-and-background-processes).

You can supress the debug logs by commenting out this line:
https://github.com/veggiedefender/torrent-client/blob/2768f3ea3d766bbd1c8cb34f9d5a5b42f837172c/p2p/p2p.go#L212

**Comment by byteshiva** [comment]
> Running `torrent-client <.torrent> <file> &` will run it in the background (note the `&`). You can read more about running a background process in bash [here](https://www.digitalocean.com/community/tutorials/how-to-use-bash-s-job-control-to-manage-foreground-and-background-processes).
> 
> You can supress the debug logs by commenting out this line:
> 
> https://github.com/veggiedefender/torrent-client/blob/2768f3ea3d766bbd1c8cb34f9d5a5b42f837172c/p2p/p2p.go#L212

Thanks, I'll fork and suppress the log files(thanks for pointing me the code line) , and background job works too 

one more questions. Is it possible to list the output files in an array or JSON format? or a string.

**Comment by crimist** [comment]
> Is it possible to list output files in an array or JSON format of torrent-client

Not really sure what you mean by this. There is only one output file from this program and it's specified with the second argument: `torrent-client <.torrent> <output-file>`

> Maybe there could be a command-line parameter to get the list or string of outputs.

This program doesn't have any extra parameters.

**Comment by byteshiva** [comment]
> > Is it possible to list output files in an array or JSON format of torrent-client
> 
> Not really sure what you mean by this. There is only one output file from this program and it's specified with the second argument: `torrent-client <.torrent> <output-file>`
> 
I got it, This is good for a single output file.
I was looking at a scenario where the torrent file could have multiples output files. In those cases how could we determine output files? Cases where there are multiple output files.

> > Maybe there could be a command-line parameter to get the list or string of outputs.
> 
> This program doesn't have any extra parameters.

**Comment by veggiedefender** [comment]
hi :)

To make implementation simpler, I decided not to support multi file torrents. It wouldn't be too hard to do though, so fork this and try it if you're up to it!

that said, this is definitely more of a toy or teaching implementation than a production ready tool. I'd recommend using a real torrent client. It'll have more features and better performance.

**Comment by byteshiva** [comment]
> hi :)
> 
> To make implementation simpler, I decided not to support multi file torrents. It wouldn't be too hard to do though, so fork this and try it if you're up to it!
> 
> that said, this is definitely more of a toy or teaching implementation than a production ready tool. I'd recommend using a real torrent client. It'll have more features and better performance.

Thanks,

**Comment by byteshiva** [comment]
I'm adding a link to open source webtorrent(I think its production-ready, it's been used by Brave Browser and others),

https://github.com/webtorrent/webtorrent-desktop
