### ISSUE TITLE
Tracker response "torrent not found" message

### ISSUE THREAD

**Issue by kelvin94** [veggiedefender/torrent-client#2]
I just cloned the project and tried out downloading with the torrent file within project folder and found the it is not working. I found out the the the tracker response from the get request contains a failure message， “torrent not found".

**Comment by veggiedefender** [comment]
Are you talking about `torrentfile/testdata/archlinux-2019.12.01-x86_64.iso.torrent`? I believe Arch's tracker only keeps around the latest few versions -- a "real" torrent client shows the same error:
![2020-06-07_22:16:50](https://user-images.githubusercontent.com/8890878/83986964-9ef85d00-a90c-11ea-970f-00963018cf5d.png)

**Comment by kelvin94** [comment]
Thx for the quick response. That's right! Learned another new thing today:)
